version: "3.8"

services:
  nextjs-app:
    image: youtube-clone
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules inside the container
    command: ["bun", "run", "dev"]
    environment:
      - NODE_ENV=development
